'use strict';

const RC5_ICON_SPRITE=CATEGORY_ICON_SPRITE;
const RC5_ICON_MAP=Object.freeze([
 [/^전체$/,'all'],[/마라|양꼬치/,'mala'],[/치킨|닭/,'chicken'],[/피자/,'pizza'],[/중식|짜장|짬뽕/,'chinese'],
 [/분식.*도시락|도시락.*분식/,'lunchbox'],[/분식|떡볶이/,'snack'],[/족발|보쌈/,'pork'],[/회|해산물|초밥|선어|수산/,'seafood'],
 [/국밥|찜|탕|찌개|조림/,'stew'],[/면|국수|냉면|우동|라멘/,'noodles'],[/고기|구이|삼겹|갈비/,'grill'],[/돈가스|돈까스|일식/,'japanese'],
 [/카페|디저트|빙수|아이스크림|커피/,'dessert'],[/야식|주점|술집/,'night'],[/햄버거|버거|샌드위치|토스트|핫도그/,'burger'],
 [/반찬/,'banchan'],[/베이커리|빵|떡/,'bakery'],[/한식/,'korean']
]);
const rc5Pointers=new Map();

function rc5IconId(name){const value=String(name||'');return RC5_ICON_MAP.find(([pattern])=>pattern.test(value))?.[1]||'other'}
function rc5Icon(name,cls='rc5-category-icon'){return `<svg class="${cls}" aria-hidden="true"><use href="${RC5_ICON_SPRITE}#${rc5IconId(name)}"></use></svg>`}
function rc5CategoryButton(name,modal=false){return modal?`<button type="button" class="${state.category===name?'active':''}" data-modal-cat="${escapeHtml(name)}">${rc5Icon(name,'rc5-category-modal-icon')}<b>${escapeHtml(name)}</b></button>`:categoryButtonMarkup(name)}
fxCategoryMarkup=name=>rc5CategoryButton(name,false);
renderCategories=renderCategoryGrid;
allCategoriesModal=function(){const names=['전체',...categories.filter(name=>name!=='전체')];openModal(`<section class="category-modal"><h2 id="modalTitle">전체 음식 카테고리</h2><div class="all-category-list rc5-category-list">${names.map(name=>rc5CategoryButton(name,true)).join('')}</div></section>`);requestAnimationFrame(()=>{$('#modal .modal-card').scrollTop=0})};

function rc5BrandKey(store){const mapped=rc2BrandKey(store);if(mapped&&mapped!==normalize(store?.name||''))return mapped;let name=String(store?.name||'').replace(/\([^)]*\)/g,'').replace(/\s+/g,' ').trim();name=name.replace(/\s+(?:여수)?[^\s]{1,10}(?:점|본점)$/,'').trim();const first=name.split(' ')[0];if(/(?:통닭|치킨|피자|버거|커피|카페)$/.test(first))return normalize(first);return normalize(name)}
function rc5PhotoKey(store){return String(fxPhoto(store)||'')}
function rc5Diversify(input){const unique=[],deferred=[],ids=new Set(),brands=new Set(),photos=new Set();for(const store of input){const id=String(store.id),brand=rc5BrandKey(store),photo=rc5PhotoKey(store);if(ids.has(id)||photo&&photos.has(photo))continue;ids.add(id);if(brands.has(brand)){deferred.push(store);continue}brands.add(brand);if(photo)photos.add(photo);unique.push(store)}for(const store of deferred){const photo=rc5PhotoKey(store),brand=rc5BrandKey(store);if(photo&&photos.has(photo)||unique.slice(-3).some(item=>rc5BrandKey(item)===brand))continue;if(unique.length>=4){unique.push(store);if(photo)photos.add(photo)}}return unique}

function rc5Card(store){const channelIcons=rc3PrimaryCardIcons(store);return `<article class="rc5-category-card" data-rc5-store="${escapeHtml(store.id)}" data-rc5-open="${escapeHtml(store.id)}"><button class="rc5-card-open" type="button">${fxCardPhoto(store)}<span class="rc5-card-copy"><h3>${escapeHtml(store.name)}</h3><p>${escapeHtml(store.area||'여수')} · ${escapeHtml(store.cat)}</p></span></button><footer><span class="rail-channel-icons" aria-label="이용 가능한 기본 주문방법">${channelIcons||'<span class="rail-method">주문방법 확인</span>'}</span></footer></article>`}
function rc5CategoryStores(){return rc5Diversify(rc4LocationSort(filteredStores().filter(store=>fxVisible(store))))}
function rc5RenderCategory({scroll=false}={}){const list=rc5CategoryStores();$('#recommendRails').hidden=true;$('#recommendRails').innerHTML='';$('#recommendSection h2').textContent=`${state.category} 가게`;$('#resetCategoryBtn').hidden=false;const grid=$('#storeGrid');grid.className='rc5-category-result-track';grid.innerHTML=list.map(rc5Card).join('')||'<p class="empty">조건에 맞는 가게가 없습니다.</p>';const more=$('#loadMoreBtn');more.hidden=!list.length;more.textContent='더보기';more.dataset.rc5More=state.category;renderCategories();$('#searchSummary').hidden=false;$('#searchSummary').innerHTML=`<span>${escapeHtml(state.category)}</span><button id="clearSearch" class="text-btn" type="button">카테고리 초기화</button>`;if(scroll)$('#recommendSection').scrollIntoView({behavior:'smooth',block:'start'})}
const rc5RenderStoresBase=renderStores;
renderStores=function(options={}){if(state.category!=='전체'&&!state.query&&!state.brandId){rc5RenderCategory(options);return}const grid=$('#storeGrid');if(grid)grid.className='store-grid';rc5RenderStoresBase(options)};
const rc5RankStoresBase=fxRankStores;
fxRankStores=spec=>rc5Diversify(rc5RankStoresBase(spec));

function rc5AddressForm(){const saved=getSavedAddress();addressDraft=saved?{...saved,coords:saved.coords||null}:{address:state.addressLabel==='여수시 전체'?'':state.addressLabel,detail:'',area:state.location,coords:state.coords,sortByDistance:false,type:'recent'};return `<div class="rc5-address-form"><header><h2 id="modalTitle">배달 주소 설정</h2></header><button class="rc5-address-launch" type="button" data-rc5-postcode-open><span>${addressDraft.address?escapeHtml(addressDraft.address):'주소를 검색해 주세요'}</span><b>주소검색</b></button><div id="addressSearchResults" class="address-search-results"><p class="rc4-address-status">주소검색에서 주소를 한 번 입력해 선택하세요.</p></div><button id="gpsLocationBtn" class="current-location-btn" type="button">⌖ <span>현재 위치 사용</span></button><div id="addressSelectedPreview" class="address-selected-preview"></div><label class="address-detail-label">상세주소<input id="addressDetailInput" value="${escapeHtml(addressDraft.detail||'')}" placeholder="동·호수, 건물명" autocomplete="address-line2"></label><button id="addressConfirmBtn" class="address-confirm-btn" type="button">이 주소로 선택 완료</button></div><section class="rc5-postcode-view" hidden><header class="rc5-postcode-head"><button type="button" class="rc5-postcode-back" data-rc5-postcode-close>← 돌아가기</button><strong>우편번호·도로명 주소검색</strong></header><div class="rc5-postcode-frame" data-rc5-postcode-frame></div></section>`}
areaModal=function(){openModal(`<section class="address-single-sheet" data-address-single>${rc5AddressForm()}</section>`);renderAddressDraft()};
async function rc5OpenPostcode(){const form=$('#modal .rc5-address-form'),view=$('#modal .rc5-postcode-view'),frame=$('#modal [data-rc5-postcode-frame]');if(!form||!view||!frame)return;form.hidden=true;view.hidden=false;frame.innerHTML='<p class="rc4-address-status">주소검색을 불러오는 중입니다.</p>';try{const Postcode=await rc4LoadPostcode();frame.innerHTML='';new Postcode({width:'100%',height:'100%',oncomplete(data){const address=String(data.roadAddress||data.jibunAddress||data.address||'').trim();if(!address){frame.innerHTML='<p class="rc5-postcode-error">선택한 주소를 확인하지 못했습니다.</p>';return}chooseAddressBase(address,{area:addressAreaFor(address),coords:null,sortByDistance:false,type:'postcode'});const label=form.querySelector('[data-rc5-postcode-open] span');if(label)label.textContent=address;form.hidden=false;view.hidden=true;renderAddressDraft();setTimeout(()=>$('#addressDetailInput')?.focus(),0)},onclose(){form.hidden=false;view.hidden=true}}).embed(frame,{autoClose:false})}catch{frame.innerHTML='<p class="rc5-postcode-error">주소검색을 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.</p>'}}
function rc5ClosePostcode(){const form=$('#modal .rc5-address-form'),view=$('#modal .rc5-postcode-view'),frame=$('#modal [data-rc5-postcode-frame]');if(frame)frame.innerHTML='';if(form)form.hidden=false;if(view)view.hidden=true}

function rc5PointerStart(event){const target=event.target.closest('[data-rc5-open]');if(!target)return;rc5Pointers.set(event.pointerId,{target,x:event.clientX,y:event.clientY,drag:false})}
function rc5PointerMove(event){const info=rc5Pointers.get(event.pointerId);if(info&&Math.hypot(event.clientX-info.x,event.clientY-info.y)>8)info.drag=true}
function rc5PointerEnd(event){const info=rc5Pointers.get(event.pointerId);if(!info)return;info.target.dataset.rc5DraggedUntil=info.drag?String(Date.now()+500):'0';rc5Pointers.delete(event.pointerId)}
function rc5HandleClick(event){const location=event.target.closest('#locationBtn,[data-open-address]');if(location){event.preventDefault();event.stopImmediatePropagation();areaModal();return}const postOpen=event.target.closest('[data-rc5-postcode-open]');if(postOpen){event.preventDefault();event.stopImmediatePropagation();rc5OpenPostcode();return}const postClose=event.target.closest('[data-rc5-postcode-close]');if(postClose){event.preventDefault();event.stopImmediatePropagation();rc5ClosePostcode();return}const category=event.target.closest('[data-cat],[data-modal-cat]');if(category){const name=category.dataset.cat||category.dataset.modalCat;if(!name)return;event.preventDefault();event.stopImmediatePropagation();const close=Boolean(category.dataset.modalCat);state.query='';state.brandId='';state.category=name;if(close)hardClose();if(name==='전체')rc3ShowAllOnHome();else rc5RenderCategory({scroll:true});return}const open=event.target.closest('[data-rc5-open]');if(open){event.preventDefault();event.stopImmediatePropagation();if(Number(open.dataset.rc5DraggedUntil||0)>Date.now())return;const store=fxStoreById(open.dataset.rc5Open);if(store)openStore(store);return}const more=event.target.closest('[data-rc5-more]');if(more){event.preventDefault();event.stopImmediatePropagation();rc4OpenCategoryAll()}}
function rc5InstallEvents(){document.addEventListener('pointerdown',rc5PointerStart,true);document.addEventListener('pointermove',rc5PointerMove,true);document.addEventListener('pointerup',rc5PointerEnd,true);document.addEventListener('pointercancel',rc5PointerEnd,true);document.addEventListener('click',rc5HandleClick,true)}
const rc5InstallEventsBase=fxInstallEvents;
fxInstallEvents=function(){rc5InstallEventsBase();rc5InstallEvents()};
