let rc6Coordinates={},rc6BannerTargets={},rc6Pointer=null;
const rc6Verified=store=>Boolean(store&&store.coordinateVerified&&Number.isFinite(store.lat)&&Number.isFinite(store.lng));
function rc6ApplyCoordinates(){canonicalStores.forEach(store=>{const row=rc6Coordinates[String(store.id)];if(row&&row.status==='verified'&&Number.isFinite(Number(row.latitude))&&Number.isFinite(Number(row.longitude))){store.lat=Number(row.latitude);store.lng=Number(row.longitude);store.coordinateSource='verified';store.coordinateVerified=true;}else{store.lat=null;store.lng=null;store.coordinateSource='';store.coordinateVerified=false;}});coordinateStores=canonicalStores.filter(rc6Verified);}
function rc6RandomizeGull(gull){const curve=()=>`${Math.round(-20+Math.random()*40)}px`,bank=()=>`${Math.round(-11+Math.random()*22)}deg`;['a','b','c','d','e'].forEach(key=>gull.style.setProperty(`--curve-${key}`,curve()));['start','a','b','c','d','end'].forEach(key=>gull.style.setProperty(`--bank-${key}`,bank()));gull.style.setProperty('--flap',`${(.44+Math.random()*.34).toFixed(2)}s`);}
function rc6Gulls(){const shell=document.querySelector('.yeosu-night-shell');if(!shell||shell.querySelector('.rc6-gulls'))return;const layer=document.createElement('div');layer.className='rc6-gulls';layer.setAttribute('aria-hidden','true');[[12,22,11,-2,.8],[20,29,13,-6,1],[27,18,9,-9,.7],[33,25,14,-3,.9]].forEach(([y,size,duration,delay,scale],i)=>{layer.insertAdjacentHTML('beforeend',`<svg class="rc6-gull" style="--y:${y}%;--size:${size}px;--duration:${duration}s;--delay:${delay}s;--scale:${scale};--x:${62+i*8}%" viewBox="0 0 32 14"><g class="rc6-gull-flap"><path d="M2 10 Q9 2 16 9 Q23 2 30 10"/></g></svg>`);const gull=layer.lastElementChild;rc6RandomizeGull(gull);gull.addEventListener('animationiteration',()=>rc6RandomizeGull(gull));});shell.prepend(layer);}
function rc6RenderHero(){const track=document.querySelector('#heroTrack');if(!track)return;if(heroCarousel)heroCarousel.destroy();track.innerHTML=HERO_BANNERS.map((banner,index)=>{const key=String(index+1).padStart(2,'0'),target=rc6BannerTargets[key]||{},mapped=target.status==='mapped'&&target.storeId;const label=mapped?`${target.label} 가게 상세 보기`:`${target.label||banner.alt} 광고`;return `<button type="button" class="carousel-slide hero-slide rc6-hero-target" data-hero-index="${index}" ${mapped?`data-rc6-banner-store="${escapeHtml(target.storeId)}"`:'aria-disabled="true"'} aria-label="${escapeHtml(label)}"><picture><source media="(max-width:520px)" srcset="${banner.mobile}"><img src="${banner.desktop}" alt="${escapeHtml(label)}" width="1200" height="700" decoding="async" loading="${index?'lazy':'eager'}"></picture></button>`}).join('');heroCarousel=new InfiniteCarousel(document.querySelector('#heroCarousel'),{interval:3500});}
function rc6HeroEvents(){const track=document.querySelector('#heroTrack');if(!track)return;track.addEventListener('pointerdown',e=>{const slide=e.target.closest('[data-rc6-banner-store]');if(!slide)return;rc6Pointer={id:e.pointerId,x:e.clientX,y:e.clientY,index:Number(slide.dataset.heroIndex),slide};},{capture:true});track.addEventListener('pointerup',e=>{if(!rc6Pointer||rc6Pointer.id!==e.pointerId)return;const p=rc6Pointer;rc6Pointer=null;const active=heroCarousel?.logicalIndex?.();if(Math.hypot(e.clientX-p.x,e.clientY-p.y)>8||!p.slide.contains(e.target)||active!==p.index)return;e.preventDefault();e.stopPropagation();const store=stores.find(item=>String(item.id)===p.slide.dataset.rc6BannerStore);if(store)openStore(store);},{capture:true});track.addEventListener('pointercancel',()=>{rc6Pointer=null},{capture:true});}
function rc6UseCurrentLocation(){const button=document.querySelector('#gpsLocationBtn');if(!button)return;if(!navigator.geolocation){button.innerHTML='⌖ <span>이 기기는 위치 기능을 지원하지 않습니다</span>';return;}button.disabled=true;button.innerHTML='⌖ <span>현재 위치 확인 중…</span>';navigator.geolocation.getCurrentPosition(position=>{button.disabled=false;const accuracy=Number(position.coords.accuracy||Infinity);if(accuracy>1000){button.innerHTML='⌖ <span>선택한 주소·동네 기준으로 보여드려요</span>';state.rc6GpsMode='fallback';return;}button.innerHTML=`⌖ <span>${accuracy<=300?'현재 위치 확인 완료':'대략적인 현재 위치 확인 완료'}</span>`;chooseAddressBase('현재 위치',{area:'여수시 전체',coords:{lat:position.coords.latitude,lng:position.coords.longitude},sortByDistance:true,type:'current'});state.locationAccuracy=accuracy;state.rc6GpsMode=accuracy<=300?'exact':'approximate';},error=>{button.disabled=false;state.rc6GpsMode='denied';button.innerHTML=`⌖ <span>${error.code===1?'선택한 주소·동네 기준으로 보여드려요':'현재 위치를 확인하지 못했습니다'}</span>`;},{enableHighAccuracy:true,timeout:10000,maximumAge:300000});}

function rc6DiversifyDistance(rows){const result=[],pending=[...rows];while(pending.length){let index=pending.findIndex(row=>!result.slice(-3).some(old=>rc5BrandKey(old.store)===rc5BrandKey(row.store)));if(index<0)index=0;result.push(pending.splice(index,1)[0]);}return result;}
function rc6ClosestNeighborhood(coords){return yeosuNeighborhoods.map(item=>({name:item.name,point:neighborhoodPoint(item.name)})).filter(item=>item.point).map(item=>({...item,distance:haversine(coords,item.point)})).sort((a,b)=>a.distance-b.distance)[0]?.name||'';}
function rc6LocationSourceRank(store){return store.locationSource==='verified-address'?1:store.locationSource==='store-name-branch'?2:store.locationSource==='notion-or-canonical-neighborhood'?3:4;}
function rc6OrderSignals(store){return{routeCount:(store.routes||[]).length,managed:Number(Boolean(store.managed)),shared:Number(Boolean(store.sharedManaged))};}
function rc6NearStores(){
 const customerHasCoords=Boolean(state.coords),selected=neighborhoodFor([state.location,state.addressLabel].join(' '))||(customerHasCoords?rc6ClosestNeighborhood(state.coords):'');
 if(!selected&&!customerHasCoords)return[];const customerPoint=customerHasCoords?state.coords:neighborhoodPoint(selected);
 const rows=canonicalStores.map(store=>{const names=store.neighborhoods?.length?store.neighborhoods:storeNeighborhoods(store),candidate=names[0]||'',same=Boolean(selected&&names.includes(selected));const actual=customerHasCoords&&rc6Verified(store)?haversine(state.coords,{lat:store.lat,lng:store.lng}):null;const candidatePoint=neighborhoodPoint(candidate),neighborhoodDistance=customerPoint&&candidatePoint?haversine(customerPoint,candidatePoint):Infinity;const sourceRank=rc6LocationSourceRank(store),signals=rc6OrderSignals(store);const bucket=same?0:candidate?1:2;return{store,candidate,bucket,actual,neighborhoodDistance,sourceRank,...signals};}).sort((a,b)=>a.bucket-b.bucket||(a.bucket===0?(Number(a.actual===null)-Number(b.actual===null)||(a.actual??Infinity)-(b.actual??Infinity)||a.sourceRank-b.sourceRank):a.neighborhoodDistance-b.neighborhoodDistance)||b.routeCount-a.routeCount||b.managed-a.managed||b.shared-a.shared||a.store.name.localeCompare(b.store.name,'ko'));
 return rc6DiversifyDistance(rows).map(row=>({...row.store,distance:row.actual,rc6SortDistance:row.actual??row.neighborhoodDistance,proximityLabel:row.actual!==null?'':row.bucket===0?`${selected}의 가게`:row.bucket===1?`${row.candidate} 주변 가게`:'여수의 다른 추천 가게',locationSource:row.store.locationSource,neighborhoodConfidence:row.store.neighborhoodConfidence}));
}
const rc6CommitAddressBase=commitAddressSelection;
function rc6CommitAddress(){if(addressDraft?.type!=='current'){rc6CommitAddressBase();return;}const coords=addressDraft.coords;if(!coords)return;state.location='여수시 전체';state.addressLabel='현재 위치';state.coords=coords;state.sortByDistance=true;sessionStorage.setItem('rc6LocationActive','1');document.querySelector('#locationText').textContent='현재 위치';hardClose();setTimeout(()=>renderStores({scroll:true,resetCount:true}),60);}
async function rc6Initialize(){[rc6Coordinates,rc6BannerTargets]=await Promise.all([fetchJson('data/store-coordinates.json',{}),fetchJson('data/banner-targets.json',{})]);rc6ApplyCoordinates();rc4StoreHasRealCoordinates=rc6Verified;fxDistance=store=>state.coords&&rc6Verified(store)?haversine(state.coords,{lat:store.lat,lng:store.lng}):null;const originalRank=fxRankStores;fxRankStores=spec=>spec.kind==='near'?rc6NearStores():originalRank(spec);useCurrentLocation=rc6UseCurrentLocation;commitAddressSelection=rc6CommitAddress;rc6RenderHero();rc6HeroEvents();rc6Gulls();renderStores({resetCount:true});fxRenderRails();document.querySelector('.build-mark').textContent='대동여수음식지도 RC6 온라인 검수 후보';}
