let rc6Coordinates={},rc6BannerTargets={},rc6Pointer=null;
const rc6Verified=store=>Boolean(store&&store.coordinateVerified&&Number.isFinite(store.lat)&&Number.isFinite(store.lng));
function rc6ApplyCoordinates(){canonicalStores.forEach(store=>{const row=rc6Coordinates[String(store.id)];if(row&&row.status==='verified'&&Number.isFinite(Number(row.latitude))&&Number.isFinite(Number(row.longitude))){store.lat=Number(row.latitude);store.lng=Number(row.longitude);store.coordinateSource='verified';store.coordinateVerified=true;}else{store.lat=null;store.lng=null;store.coordinateSource='';store.coordinateVerified=false;}});coordinateStores=canonicalStores.filter(rc6Verified);}
function rc6Gulls(){const shell=document.querySelector('.yeosu-night-shell');if(!shell||shell.querySelector('.rc6-gulls'))return;const layer=document.createElement('div');layer.className='rc6-gulls';layer.setAttribute('aria-hidden','true');[[12,22,11,-2,.8],[20,29,13,-6,1],[27,18,9,-9,.7],[33,25,14,-3,.9]].forEach(([y,size,duration,delay,scale],i)=>{layer.insertAdjacentHTML('beforeend',`<svg class="rc6-gull" style="--y:${y}%;--size:${size}px;--duration:${duration}s;--delay:${delay}s;--scale:${scale};--x:${62+i*8}%" viewBox="0 0 32 14"><path d="M2 10 Q9 2 16 9 Q23 2 30 10"/></svg>`)});shell.prepend(layer);}
function rc6RenderHero(){const track=document.querySelector('#heroTrack');if(!track)return;if(heroCarousel)heroCarousel.destroy();track.innerHTML=HERO_BANNERS.map((banner,index)=>{const key=String(index+1).padStart(2,'0'),target=rc6BannerTargets[key]||{},mapped=target.status==='mapped'&&target.storeId;const label=mapped?`${target.label} 가게 상세 보기`:`${target.label||banner.alt} 광고`;return `<button type="button" class="carousel-slide hero-slide rc6-hero-target" data-hero-index="${index}" ${mapped?`data-rc6-banner-store="${escapeHtml(target.storeId)}"`:'aria-disabled="true"'} aria-label="${escapeHtml(label)}"><picture><source media="(max-width:520px)" srcset="${banner.mobile}"><img src="${banner.desktop}" alt="${escapeHtml(label)}" width="1200" height="700" decoding="async" loading="${index?'lazy':'eager'}"></picture></button>`}).join('');heroCarousel=new InfiniteCarousel(document.querySelector('#heroCarousel'),{interval:3500});}
function rc6HeroEvents(){const track=document.querySelector('#heroTrack');if(!track)return;track.addEventListener('pointerdown',e=>{const slide=e.target.closest('[data-rc6-banner-store]');if(!slide)return;rc6Pointer={id:e.pointerId,x:e.clientX,y:e.clientY,index:Number(slide.dataset.heroIndex),slide};},{capture:true});track.addEventListener('pointerup',e=>{if(!rc6Pointer||rc6Pointer.id!==e.pointerId)return;const p=rc6Pointer;rc6Pointer=null;const active=heroCarousel?.logicalIndex?.();if(Math.hypot(e.clientX-p.x,e.clientY-p.y)>8||!p.slide.contains(e.target)||active!==p.index)return;e.preventDefault();e.stopPropagation();const store=stores.find(item=>String(item.id)===p.slide.dataset.rc6BannerStore);if(store)openStore(store);},{capture:true});track.addEventListener('pointercancel',()=>{rc6Pointer=null},{capture:true});}
function rc6UseCurrentLocation(){const button=document.querySelector('#gpsLocationBtn');if(!button)return;if(!navigator.geolocation){button.innerHTML='⌖ <span>이 기기는 위치 기능을 지원하지 않습니다</span>';return;}button.disabled=true;button.innerHTML='⌖ <span>현재 위치 확인 중…</span>';navigator.geolocation.getCurrentPosition(position=>{button.disabled=false;const accuracy=Number(position.coords.accuracy||Infinity);if(accuracy>1000){button.innerHTML='⌖ <span>선택한 주소·동네 기준으로 보여드려요</span>';state.rc6GpsMode='fallback';return;}button.innerHTML=`⌖ <span>${accuracy<=300?'현재 위치 확인 완료':'대략적인 현재 위치 확인 완료'}</span>`;chooseAddressBase('현재 위치',{area:'여수시 전체',coords:{lat:position.coords.latitude,lng:position.coords.longitude},sortByDistance:true,type:'current'});state.locationAccuracy=accuracy;state.rc6GpsMode=accuracy<=300?'exact':'approximate';},error=>{button.disabled=false;state.rc6GpsMode='denied';button.innerHTML=`⌖ <span>${error.code===1?'선택한 주소·동네 기준으로 보여드려요':'현재 위치를 확인하지 못했습니다'}</span>`;},{enableHighAccuracy:true,timeout:10000,maximumAge:300000});}

function rc6DiversifyDistance(rows){const result=[],pending=[...rows];while(pending.length){let index=pending.findIndex(row=>!result.slice(-3).some(old=>rc5BrandKey(old.store)===rc5BrandKey(row.store)));if(index<0)index=0;result.push(pending.splice(index,1)[0]);}return result;}
const RC6_NEIGHBORHOOD_ZONES={
 '여서동':'west','문수동':'west','미평동':'west','둔덕동':'west','오림동':'west','광무동':'west',
 '고소동':'oldtown','교동':'oldtown','중앙동':'oldtown','충무동':'oldtown','공화동':'oldtown','관문동':'oldtown','종화동':'oldtown','수정동':'oldtown','덕충동':'oldtown',
 '국동':'southwest','신월동':'southwest','봉산동':'southwest',
 '학동':'yeocheon','신기동':'yeocheon','선원동':'yeocheon','화장동':'yeocheon','안산동':'yeocheon','소호동':'yeocheon','웅천동':'yeocheon',
 '죽림':'outer','소라':'outer','율촌':'outer','돌산':'island'
};
const RC6_ZONE_NEIGHBORS={west:['southwest','oldtown'],southwest:['west','oldtown'],oldtown:['southwest','west'],yeocheon:['outer'],outer:['yeocheon'],island:['oldtown']};
function rc6NeighborhoodTier(selected,candidate){if(!selected||!candidate)return 9;if(selected===candidate)return 0;const a=RC6_NEIGHBORHOOD_ZONES[selected],b=RC6_NEIGHBORHOOD_ZONES[candidate];if(a&&a===b)return 1;if(a&&b&&RC6_ZONE_NEIGHBORS[a]?.includes(b))return 2;return 3;}
function rc6TierLabel(tier){return tier===0?'같은 동네':tier===1?'가까운 권역':tier===2?'인접 권역':'다른 권역';}
function rc6NearStores(){
 if(state.coords){const rows=coordinateStores.map(store=>({store,distance:haversine(state.coords,{lat:store.lat,lng:store.lng})})).sort((a,b)=>a.distance-b.distance);return rc6DiversifyDistance(rows).map(row=>({...row.store,distance:state.rc6GpsMode==='exact'?row.distance:null,rc6SortDistance:row.distance,proximityLabel:state.rc6GpsMode==='exact'?'실제 거리순':'현재 위치 기준'}));}
 const selected=neighborhoodFor([state.location,state.addressLabel].join(' '));if(!selected)return[];
 const rows=canonicalStores.map(store=>{const candidate=storeNeighborhoods(store)[0]||'';return{store,tier:rc6NeighborhoodTier(selected,candidate),candidate};}).filter(row=>row.tier<9).sort((a,b)=>a.tier-b.tier||a.store.name.localeCompare(b.store.name,'ko'));
 return rc6DiversifyDistance(rows).map(row=>({...row.store,distance:null,rc6SortDistance:null,proximityLabel:rc6TierLabel(row.tier)}));
}
const rc6CommitAddressBase=commitAddressSelection;
function rc6CommitAddress(){if(addressDraft?.type!=='current'){rc6CommitAddressBase();return;}const coords=addressDraft.coords;if(!coords)return;state.location='여수시 전체';state.addressLabel='현재 위치';state.coords=coords;state.sortByDistance=true;sessionStorage.setItem('rc6LocationActive','1');document.querySelector('#locationText').textContent='현재 위치';hardClose();setTimeout(()=>renderStores({scroll:true,resetCount:true}),60);}
async function rc6Initialize(){[rc6Coordinates,rc6BannerTargets]=await Promise.all([fetchJson('data/store-coordinates.json',{}),fetchJson('data/banner-targets.json',{})]);rc6ApplyCoordinates();rc4StoreHasRealCoordinates=rc6Verified;fxDistance=store=>state.coords&&rc6Verified(store)?haversine(state.coords,{lat:store.lat,lng:store.lng}):null;const originalRank=fxRankStores;fxRankStores=spec=>spec.kind==='near'?rc6NearStores():originalRank(spec);useCurrentLocation=rc6UseCurrentLocation;commitAddressSelection=rc6CommitAddress;rc6RenderHero();rc6HeroEvents();rc6Gulls();renderStores({resetCount:true});fxRenderRails();document.querySelector('.build-mark').textContent='대동여수음식지도 RC6 온라인 검수 후보';}
